openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a The Oasis Luxury API server.
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

paths:
  /api/v1/users/register:
   post:
    description: Register new user
    tags:
      - Users
    requestBody:
      description: Register new user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RegisterReqBody'
      required: true
    responses:
      200:
        description: Register success
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: Register success
                result:
                  $ref: '#/components/schemas/User'
      400:
        description: Register failed